version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.0
    steps:
      - checkout
      - run:
          name: Ensure composer.lock exists
          command: |
            if [ ! -f ./composer.lock ]; then
              echo "composer.lock not found! Exiting."
              exit 1
            fi
      - restore_cache:
          keys:
            - composer-cache-{{ checksum "composer.lock" }}
            - composer-cache-
      - run:
          name: Install dependencies
          command: composer install --prefer-dist --no-interaction
      - save_cache:
          paths:
            - ~/.composer/cache
          key: composer-cache-{{ checksum "composer.lock" }}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build